version: '3.5'

services:
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - data-engineering-network
    ports:
      - '27017:27017'

  twitter-storage:
    container_name: twitter-storage
    build: 
      context: ./storage
      dockerfile: twitter.Dockerfile
    image: twitter-storage:latest
    networks:
      - data-engineering-network

  crypto-storage:
    container_name: crypto-storage
    build: 
      context: ./storage
      dockerfile: crypto.Dockerfile
    image: crypto-storage:latest
    networks:
      - data-engineering-network

networks:
  data-engineering-network:
   name: data-engineering-network