version: '3.5'

services:
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - data-engineering-network
    ports:
      - '27017:27017'
    logging:
      driver: none

  storage:
    container_name: storage
    build: 
      context: ./storage
      dockerfile: Dockerfile
    image: storage:latest
    networks:
      - data-engineering-network

networks:
  data-engineering-network:
   name: data-engineering-network